<?php
/**
 * English language file for config
 *
 */

$lang['discussionPage']   = 'Discussion page (leave empty to disable discussions)';
$lang['userPage']         = 'User page (leave empty to disable user pages)';
$lang['hideTools']        = 'Hide tools when not logged in?';
$lang['menuID']           = 'ID of menu generated by nav-plugin';
$lang['footerID']         = 'ID of footer page';
$lang['headerImg']        = 'URL of a different header image (leave empty for default)';